---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fight-service
  labels:
    app: fight-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: fight-service
  template:
    metadata:
      labels:
        app: fight-service
    spec:
      containers:
      - name: fight-service
        image: workshop/fight-service:latest
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: IfNotPresent

        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /q/health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
