---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: villain-postgres
spec:
  selector:
    matchLabels:
      app: villain-service-database
  template:
    metadata:
      labels:
        app: villain-service-database
    spec:
      containers:
        - name: postgres
          image: postgres:9.6.5
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: villain-service
            - name: POSTGRES_USER
              value: villain-service
            - name: POSTGRES_PASSWORD
              value: villain-service

---
apiVersion: v1
kind: Service
metadata:
  name: villain-service-database
spec:
  ports:
    - port: 5432
  selector:
    app: villain-service-database
