---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: villain-service-monolith
  labels:
    app: villain-service-monolith
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: villain-service-monolith
  template:
    metadata:
      labels:
        app: villain-service-monolith
    spec:
      containers:
      - name: villain-service-monolith
        image: workshop/villain-service:latest
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: IfNotPresent
        env:
          - name: QUARKUS_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: villain-service-config
                key: database
          - name: QUARKUS_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: villain-service-database-secret
                key: username
          - name: QUARKUS_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: villain-service-database-secret
                key: password
