---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: viallain-service
  labels:
    app: viallain-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: first-service
  template:
    metadata:
      labels:
        app: first-service
    spec:
      containers:
      - name: first-service
        image: workshop/first-service-jvm:1.1
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: IfNotPresent

        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /q/health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supes-monolith
  labels:
    app: supes-monolith
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: supes-monolith
  template:
    metadata:
      labels:
        app: supes-monolith
    spec:
      containers:
      - name: supes-monolith
        image: workshop/supes-monolith:latest
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: IfNotPresent
        env:
          - name: QUARKUS_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: supes-config
                key: database
          - name: QUARKUS_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: supes-database-secret
                key: username
          - name: QUARKUS_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: supes-database-secret
                key: password