---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: villain-service
  labels:
    app: villain-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: villain-service
  template:
    metadata:
      labels:
        app: villain-service
    spec:
      containers:
      - name: villain-service
        image: workshop/villain-service-jvm
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: IfNotPresent

        env:
        - name: QUARKUS_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: villain-config
              key: database
        - name: QUARKUS_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: villain-database-secret
              key: username
        - name: QUARKUS_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: villain-database-secret
              key: password


       