---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hero-service
  labels:
    app: hero-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: hero-service
  template:
    metadata:
      labels:
        app: hero-service
    spec:
      containers:
      - name: hero-service
        image: workshop/hero-service:latest
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: IfNotPresent
        env:
          - name: QUARKUS_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: hero-config
                key: database
          - name: QUARKUS_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: hero-database-secret
                key: username
          - name: QUARKUS_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hero-database-secret
                key: password

        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /q/health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
